"""empty message

Revision ID: 15071cb5a490
Revises: 8f4fbe338bd6
Create Date: 2019-02-03 19:22:58.845456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15071cb5a490'
down_revision = '8f4fbe338bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET admin=False')
    op.alter_column('users', 'admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
